### PR TITLE
Add SodionAuthHook

### PR DESCRIPTION
**Pull request by ishland**
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (If your work is in progress, please consider making a draft pull request.)

### Summary of your change
[//]: # (Example: motiviation, enhancement)
Add SodionAuthHook

### Related issue
[//]: # (Reference it using '#NUMBER'. Ex: Fixes/Related #...)
Fixes https://github.com/Mohist-Community/SodionAuth/issues/13

### CODE REVIEW

**Comment by ishland** [comment]
Note that JitPack Queue is currently down, I need additional check until I mark this as ready for review

**Comment by games647** [comment]
But make sure that your methods are thread-safe. FastLogin will call those methods asynchronous.

**Comment by ishland** [comment]
Those methods are thread-safe.

**Comment by games647** [comment]
Okay, just wanted to make sure. A lot of people don't do it correctly.

**Comment by games647** [comment]
BTW: GitHub also supports hosting Maven repository using GitHub packages.

**Comment by ishland** [comment]
GitHub repository requires additional configuration to use, so I did not use it

**Pull request merged**
