### PR TITLE
Fix NPE on getting lastLogin Timestamp from database

### PR DESCRIPTION
**Pull request by ptrcnull**

### CODE REVIEW

**Comment by ptrcnull** [comment]
Currently on my BungeeCord server it throws following NPE:
```
[02:30:52 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@19fb8826, id=63, owner=com.github.games647.fastlogin.bungee.FastLoginBungee@17740dae, task=com.github.games647.fastlogin.bungee.task.AsyncToggleMessage@68f74e78, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException: null
at com.github.games647.fastlogin.core.AuthStorage.parseResult(AuthStorage.java:129) ~[?:?]
at com.github.games647.fastlogin.core.AuthStorage.loadProfile(AuthStorage.java:96) ~[?:?]
at com.github.games647.fastlogin.bungee.task.AsyncToggleMessage.activatePremium(AsyncToggleMessage.java:53) ~[?:?]
at com.github.games647.fastlogin.bungee.task.AsyncToggleMessage.run(AsyncToggleMessage.java:32) ~[?:?]
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[waterfall-312.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by games647** [comment]
This shouldn't happen, because LastLogin is defined to be Not Null in SQL. Is your current database scheme different?

**Comment by ptrcnull** [comment]
image

Apparently, none of them are not null.

**Comment by games647** [comment]
Do you created the table yourself? I just tried to create it on a MariaDB instance and it was correctly created.

describe

**Comment by ptrcnull** [comment]
Nope, the plugin created it for me (around 3/4 months ago).
My database is also MariaDB, version 10.2.29.

**Comment by games647** [comment]
That's weird, even the very old FastLogin 1.10 used `Not NULL`

**Comment by ptrcnull** [comment]
> Do you have another source that inserts values into this table?

Nope, only FastLoginBukkit/Bungee

> Do you used MariaDB at that time too with the same version?

No, 10.2.29 was the newest version since I set it all up.

**Comment by games647** [comment]
>No, 10.2.29 was the newest version since I set it all up.

So I tried it on a docker instance for 10.2.29. I created the same correct table structure. Could you try to run `describe premium` in SQL? Maybe your view only shows the column data types.

**Comment by ptrcnull** [comment]
Hey, sorry for inactivity, I forgot about this.
It seems like FastLogin has more issues with database, maybe it's because of the driver or my database, but it tends to create duplicate rows with `UserID`, `UUID` and `LastLogin` set to null, when I added unique index to `Name` that's what I see (after one row has been added with NULL values):
```
[FastLogin]: Failed to save playerProfile StoredProfile{rowId=-1, premium=false, lastIp='[CENSORED]', lastLogin=2020-05-02T10:25:48.972Z} StoredProfile{id=null, name='[CENSORED]'}
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '[CENSORED]' for key 'premium_Name_uindex'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_242]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_242]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
        <cut>
        at fastlogin.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[?:?]
        at fastlogin.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[?:?]
        at com.github.games647.fastlogin.core.AuthStorage.save(AuthStorage.java:154) ~[?:?]
        at com.github.games647.fastlogin.core.shared.ForceLoginManagement.run(ForceLoginManagement.java:64) ~[?:?]
        at com.github.games647.fastlogin.bungee.task.ForceLoginTask.run(ForceLoginTask.java:40) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[waterfall-327.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
```
The row added before:
obraz

**Comment by games647** [comment]
>UserID, UUID and LastLogin set to null

Please check your table schema. FastLogin creates the table with auto incrementing primary keys. So null should never be inserted.

**Comment by ptrcnull** [comment]
Here's the schema:
```
MariaDB [(none)]> DESCRIBE `fastlogin`.premium;
+-----------+------------+------+-----+---------------------+-------+
| Field     | Type       | Null | Key | Default             | Extra |
+-----------+------------+------+-----+---------------------+-------+
| UserID    | int(11)    | YES  |     | NULL                |       |
| UUID      | char(36)   | YES  |     | NULL                |       |
| Name      | tinytext   | NO   | UNI | NULL                |       |
| Premium   | tinyint(4) | NO   |     | NULL                |       |
| LastIp    | tinytext   | NO   |     | NULL                |       |
| LastLogin | timestamp  | NO   |     | current_timestamp() |       |
+-----------+------------+------+-----+---------------------+-------+
6 rows in set (0.001 sec)
```

**Comment by ptrcnull** [comment]
...and after deleting current table, I see the schema is supposed to be different:
```
MariaDB [(none)]> DESCRIBE `fastlogin`.premium;
+-----------+--------------+------+-----+---------------------+----------------+
| Field     | Type         | Null | Key | Default             | Extra          |
+-----------+--------------+------+-----+---------------------+----------------+
| UserID    | int(11)      | NO   | PRI | NULL                | auto_increment |
| UUID      | char(36)     | YES  |     | NULL                |                |
| Name      | varchar(16)  | NO   | UNI | NULL                |                |
| Premium   | tinyint(1)   | NO   |     | NULL                |                |
| LastIp    | varchar(255) | NO   |     | NULL                |                |
| LastLogin | timestamp    | NO   |     | current_timestamp() |                |
+-----------+--------------+------+-----+---------------------+----------------+
6 rows in set (0.001 sec)
```
I think my old database may have been the issue, because I tried regenerating before and it was still creating a wrong schema, it's fixed after I updated MariaDB to 10.4.

**Comment by games647** [comment]
Then I'll close it. However it's strange that such a bug was released to the bug.

**Pull request closed without merging**
