### PR TITLE
Update ProtocolSupport version to support latest ProtocolSupport development builds

### PR DESCRIPTION
**Pull request by ishland**

### CODE REVIEW

**Comment by ishland** [comment]
Tested on git-Paper-234 (MC: 1.14.4)
with ProtocolSupport 03cd0161f6277eb41ce8311741fb2564df88ce41 build 456
ViaVersion 2.1.4-1.15-pre6 build 296
ProtocolLib 4.5.0 build 429

**Comment by games647** [comment]
Were there any incompatible changes? Normally it shouldn't be necessary to upgrade the dependency version.

**Comment by ishland** [comment]
Yep, but if you don't update the dependency version, it is incompatible with newer ProtocolSupport.
I will test this on lower versions later.

**Comment by games647** [comment]
This would mean that were some binary incompatible changes, because nothing of the API usage has changed. This unlikely, but can happen.

**Pull request closed without merging**
